Azure-Samples/azure-typescript-e2e-apps

api/.vscode/extensions.json
api/.vscode/launch.json
api/.vscode/settings.json
api/.vscode/tasks.json
api/jest.config.js
api/package.json
api/src/functions/status.test.ts
api/src/functions/status.ts
api/tsconfig.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Feature: add basic test to basic api

---

api-expressjs-openapi-azuresql-js/.env.development.sample
api-expressjs-openapi-azuresql-js/.gitignore
api-expressjs-openapi-azuresql-js/.vscode/launch.json
api-expressjs-openapi-azuresql-js/README.md
api-expressjs-openapi-azuresql-js/config.js
api-expressjs-openapi-azuresql-js/database.js
api-expressjs-openapi-azuresql-js/index.js
api-expressjs-openapi-azuresql-js/mssql-no-password.js
api-expressjs-openapi-azuresql-js/openapi.js
api-expressjs-openapi-azuresql-js/package.json
api-expressjs-openapi-azuresql-js/person.js
api-expressjs-openapi-azuresql-js/sql/create-azure-sql-user.sql

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

move to esm

---

app-react-vite-openai-chat/chat-script.sh
app-react-vite-openai-chat/messages.example.json
app-react-vite-openai-chat/src/App.css
app-react-vite-openai-chat/src/App.tsx
app-react-vite-openai-chat/src/components/Message.tsx
app-react-vite-openai-chat/src/index.css

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Azure OpenAI React chat client with Vite

---

scripts/openai-request.js
scripts/package-lock.json
scripts/package.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

openai request with node-fetch

---

cli-openai/src/index.ts
lib-openai/example.request.json
lib-openai/example.response.json
lib-openai/package.json
lib-openai/src/index.ts
lib-openai/src/models.ts

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

OpenAi updates

---

azure-upload-file-to-storage/api-functions-v4-upload-file/src/functions/list.ts
azure-upload-file-to-storage/api-functions-v4-upload-file/src/functions/sas.ts
azure-upload-file-to-storage/api-functions-v4-upload-file/src/lib/azure-storage.ts
azure-upload-file-to-storage/app-react-vite-file-upload/src/App.tsx
azure-upload-file-to-storage/app-react-vite-file-upload/src/components/error-boundary.tsx

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Updates to swa + api file upload

---

azure-upload-file-to-storage/api/package.json
azure-upload-file-to-storage/app/package.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

update upload file's package.json files

---

azure-upload-file-to-storage/api/package.json
azure-upload-file-to-storage/api/src/lib/azure-storage.ts
azure-upload-file-to-storage/app/.env
azure-upload-file-to-storage/app/package.json
azure-upload-file-to-storage/app/src/App.tsx
azure-upload-file-to-storage/app/vite.config.dev.ts

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

SWA + FN - fixes

---

azure-upload-file-to-storage/api/package.json
azure-upload-file-to-storage/api/src/functions/sas.ts
azure-upload-file-to-storage/api/src/lib/azure-storage.ts
azure-upload-file-to-storage/app/package.json
azure-upload-file-to-storage/app/src/App.tsx
azure-upload-file-to-storage/app/src/lib/convert-file-to-arraybuffer.ts
azure-upload-file-to-storage/hello.txt

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

new conversation fn, add material ui

---

resources/2024-js-dev-day.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

2024 JS Dev Day

---

.devcontainer/devcontainer.json
.gitignore
quickstarts/azure-openai-assistants/package-lock.json
quickstarts/azure-openai-assistants/package.json
quickstarts/azure-openai-assistants/readme.md
quickstarts/azure-openai-assistants/sample.env
quickstarts/azure-openai-assistants/scripts/create-azure-resource.sh
quickstarts/azure-openai-assistants/src/index-using-password.ts
quickstarts/azure-openai-assistants/src/index.ts
quickstarts/azure-openai-assistants/tsconfig.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Azure OpenAI Assistants

---

quickstarts/azure-openai-assistants/src/index-using-password.ts
quickstarts/azure-openai-assistants/src/index.ts

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Azure OpenAI Assistant - quickstart types

---

quickstarts/azure-openai-assistants/js/package.json
quickstarts/azure-openai-assistants/js/src/index-using-password.mjs
quickstarts/azure-openai-assistants/js/src/index.mjs
quickstarts/azure-openai-assistants/ts/package.json
quickstarts/azure-openai-assistants/ts/src/index-using-password.ts
quickstarts/azure-openai-assistants/ts/src/index.ts

* ...
```
[x] Yes
[ ] No
```
Updates the JS quickstarts to use the new client library for Azure OpenAI.
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...

Use openai SDK instead of @azure/openai

---

app-react-vite/src/App.tsx
app-react-vite/src/Components/NavBar.tsx
app-react-vite/src/Components/Status.tsx

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

SWA CLI Entra ID migration

---

api-expressjs-openapi-azuresql-js/database.js
api-expressjs-openapi-azuresql-js/mssql-no-password.js
api-expressjs-openapi-azuresql-js/person.js
api-expressjs-openapi-azuresql/mssql-no-password.js
api-expressjs-openapi-azuresql/src/config.ts
api-expressjs-openapi-azuresql/src/routes/person.ts
api-expressjs-vm/index-logging.js

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

CodeQL changes

---

api-expressjs-openapi-azuresql-js/README.md
api-expressjs-openapi-azuresql/README.md
api-expressjs-openapi-inmemory/README.md
api-expressjs-vm/readme.md
api/README.md
api/local.settings.json
api/local.settings.sample.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

README updates

---

SECURITY.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Add Security.md

---

api-functions-v4-azure-resource-management/README.md

Functions and storage information for security, Samples browser metadata.
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fn + Resource groups

---

api-expressjs-vm/readme.md
api-functions-v4-azure-resource-management/README.md
app-react-vite/README.md
azure-upload-file-to-storage/README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Samples browser

---

quickstarts/azure-sql/connect-and-query/README.md
quickstarts/azure-sql/connect-and-query/js/database.js
quickstarts/azure-sql/connect-and-query/ts/src/dbazuresql.ts

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Create table if development

---

quickstarts/storage/index.js
quickstarts/storage/package-lock.json
quickstarts/storage/package.json
sdk/chained-credentials/chained-token-credential.js
sdk/chained-credentials/custom-tenant-credential.js
sdk/chained-credentials/debug-chained-credential.js
sdk/chained-credentials/default-azure-credential.js
sdk/chained-credentials/managed-identity-credential.js
sdk/chained-credentials/package.json
sdk/chained-credentials/user-assigned-managed-identity.js
sdk/chained-credentials/why-use-credential-chains.js
sdk/chained-credentials/workload-identity.js

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

SDK Credential Chains

---

api-expressjs-vm/package-lock.json
api-expressjs-vm/package.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Updated api-express-vm

---

quickstarts/service-bus/README.md

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

add readme for service bus quickstarts

---

.devcontainer/devcontainer.json
ts-boilerplate-common/.gitignore
ts-boilerplate-common/http/get-root.http
ts-boilerplate-common/http/post-api.http
ts-boilerplate-common/http/post-data.http
ts-boilerplate-common/package-lock.json
ts-boilerplate-common/package.json
ts-boilerplate-common/readme.md
ts-boilerplate-common/src/index.ts
ts-boilerplate-common/src/public/index.html
ts-boilerplate-common/src/public/styles.css
ts-boilerplate-common/tsconfig.json
ts-boilerplate-esm/.gitignore
ts-boilerplate-esm/.prettierignore
ts-boilerplate-esm/.prettierrc
ts-boilerplate-esm/http/get-root.http
ts-boilerplate-esm/http/post-data.http
ts-boilerplate-esm/package-lock.json
ts-boilerplate-esm/package.json
ts-boilerplate-esm/readme.md
ts-boilerplate-esm/src/index.ts
ts-boilerplate-esm/tsconfig.json

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

TS boilerplate Common & ESM
